### ISSUE TITLE
Error 2347-0026 when exiting.

### ISSUE THREAD

**Issue by uumas** [vgmoose/spacenx#1]
When I press B in the main menu to exit from the game back to hbl I get error 2347-0026 and am forced to reboot the console. If I use the home button to exit to home menu it works fine.

**Comment by vgmoose** [comment]
I suspect this stems from https://github.com/reswitched/libtransistor/issues/110, I don't know much else about it however

**Comment by vgmoose** [comment]
I think this is now addressed in d09ff27 with the [latest release](https://github.com/vgmoose/spacenx/releases)
